### ISSUE TITLE
learn for my thesis

### ISSUE THREAD

**Issue by wulandarzki** [martinwhl/Informer-PyTorch-Lightning#2]
hello, actually I'm still learning about informer but I will use it for my thesis in the future. I am gonna ask cause u separated the file encoder, decoder, and main informer, is it necessary to separate them? (I'm not really good at machine learning actually but I'm happy to learn about it and still confused about that) thank you so much

**Comment by martinwhl** [comment]
No, it isn't. But I personally don't think that it is a good habit to put all the stuff in one file.

**Comment by wulandarzki** [comment]
thank you so much for your answer!
